/**
 * Weiterleitungen von den alten Google-Sites-URLs.
 * Erzeugt von scripts/migration/convert.ts.
 *
 * Deutsch (dok.smart-me.com): alle Pfade wurden 1:1 als Slug übernommen,
 * nur /home liegt neu auf /.
 *
 * Englisch (doc.smart-me.com): die englischen Seiten liegen neu unter dem
 * deutschen Slug, damit das Locale-Dropdown zwischen den Sprachfassungen
 * derselben Seite wechselt. Die Regeln greifen im en-Build mit dem
 * Sprachpräfix, also /en/<alt> -> /en/<neu>.
 */
export type Redirect = {from: string | string[]; to: string};

export const redirects: Redirect[] = [
  {from: '/home', to: '/'},

  // Alte englische Pfade
  {from: '/configuration/applab', to: '/konfiguration/applab'},
  {from: '/configuration/billing', to: '/konfiguration/billing'},
  {from: '/configuration/billing/define-electrical-tariffs', to: '/konfiguration/billing/stromtarife-definieren'},
  {from: '/configuration/billing/mieterstrom', to: '/konfiguration/billing/mieterstrom'},
  {from: '/configuration/billing/vewa-billing', to: '/konfiguration/billing/vewa-abrechnung'},
  {from: '/configuration/billing/virtual-meters', to: '/konfiguration/billing/virtuelle-zaehler'},
  {from: '/configuration/commissioning', to: '/konfiguration/inbetriebnahme'},
  {from: '/configuration/commissioning/commissioning-lora', to: '/konfiguration/inbetriebnahme/inbetriebnahme-lora'},
  {from: '/configuration/commissioning/delete-meter', to: '/konfiguration/inbetriebnahme/zaehler-loeschen'},
  {from: '/configuration/commissioning/pico-configuration', to: '/konfiguration/inbetriebnahme/pico-konfiguration'},
  {from: '/configuration/creating-users', to: '/konfiguration/benutzerkonfiguration'},
  {from: '/configuration/firmware-update', to: '/konfiguration/firmware-update'},
  {from: '/configuration/folder-configuration', to: '/konfiguration/ordnerkonfiguration'},
  {from: '/configuration/if-then-action', to: '/konfiguration/wenndann-aktionen'},
  {from: '/configuration/if-then-action/alarms', to: '/konfiguration/wenndann-aktionen/alarme'},
  {from: '/configuration/if-then-action/event-related-actions', to: '/konfiguration/wenndann-aktionen/ereignisaktionen'},
  {from: '/configuration/if-then-action/examples-of-boiler-control-with-ifthen-actions', to: '/konfiguration/wenndann-aktionen/beispiel-boilersteuerung'},
  {from: '/configuration/multilevel-load-management', to: '/konfiguration/multilevel-lastmanagement'},
  {from: '/configuration/multilevel-load-management/configure-the-mlm', to: '/konfiguration/multilevel-lastmanagement/mlm-konfigurieren'},
  {from: '/configuration/my-dashboards', to: '/konfiguration/my-dashboards'},
  {from: '/contact', to: '/kontakt'},
  {from: '/information-security/data-security', to: '/informationssicherheit/datensicherheit'},
  {from: '/information-security/meter-transactions', to: '/informationssicherheit/zählertransaktionen'},
  {from: '/information-security/public-key-signature', to: '/informationssicherheit/public-key-signature'},
  {from: '/interfaces/ai-connector', to: '/schnittstellen/ai-connector'},
  {from: '/interfaces/api', to: '/schnittstellen/api'},
  {from: '/interfaces/auto-export', to: '/schnittstellen/auto-export'},
  {from: '/interfaces/dta-vhka-files', to: '/schnittstellen/dta-vhka-files'},
  {from: '/interfaces/ebix-data-import', to: '/schnittstellen/ebix-datenimport'},
  {from: '/interfaces/input-and-output-configuration', to: '/schnittstellen/ein_und_ausgaenge'},
  {from: '/interfaces/minergie-exporter', to: '/schnittstellen/minergie-exporter'},
  {from: '/interfaces/modbus-tcp', to: '/schnittstellen/modbus-tcp'},
  {from: '/interfaces/swisseldex-data-import', to: '/schnittstellen/swisseldex-sdat-import'},
  {from: '/planning', to: '/planung'},
  {from: '/planning/certification-calibration', to: '/planung/zertifizierungen'},
  {from: '/planning/cloud-licence', to: '/planung/cloud-lizenzen'},
  {from: '/planning/contract-legal', to: '/planung/vertrag-rechtliches'},
  {from: '/planning/e-mobility', to: '/planung/elektromobilitaet'},
  {from: '/planning/e-mobility_1', to: '/planung/e-mobility'},
  {from: '/planning/internet-connection', to: '/planung/internetverbindung'},
  {from: '/planning/measurement-concept-producers-behind-houses', to: '/planung/messkonzept-produzenten-hinter-haeuser'},
  {from: '/planning/measurement-concepts-emergency-power-solutions', to: '/planung/Messkonzept-Notstromloesung'},
  {from: '/planning/minergie', to: '/planung/minergie'},
  {from: '/planning/prepare-billing', to: '/planung/abrechnung-vorbereiten'},
  {from: '/planning/virtual-zev-vzev', to: '/planung/virtuelle-zev-vzev'},
  {from: '/products', to: '/produkte'},
  {from: '/products/3-phase-meter', to: '/produkte/3-phasen-zähler'},
  {from: '/products/3-phase-meter-nimbus-100a', to: '/produkte/nimbus'},
  {from: '/products/3-phase-meter-telstar', to: '/produkte/telstar'},
  {from: '/products/discontinued-products', to: '/produkte/eingestellte-produkte'},
  {from: '/products/kamstrup-module', to: '/produkte/kamstrup-modul'},
  {from: '/products/landis-gyr-module', to: '/produkte/landis-gyr-modul'},
  {from: '/products/m-bus-gateway', to: '/produkte/m-bus-gateway'},
  {from: '/products/pico-ev-charger', to: '/produkte/pico-ladestation'},
  {from: '/products/pico-ev-charger-exa', to: '/produkte/pico-ladestation-exa'},
  {from: '/products/pico-ev-charger/pico-accessories', to: '/produkte/pico-ladestation/pico-zubehör'},
  {from: '/products/pico-ev-charger/pico-display', to: '/produkte/pico-ladestation/pico-display'},
  {from: '/products/pico-ev-charger/pico-load-management', to: '/produkte/pico-ladestation/pico-lastmanagement'},
  {from: '/products/pico-ev-charger/pico-stand', to: '/produkte/pico-ladestation/pico-standfuss'},
  {from: '/products/plug', to: '/produkte/plug'},
  {from: '/products/single-phase-meter', to: '/produkte/1-phasen-zaehler'},
  {from: '/products/smart-eye', to: '/produkte/smart-eye'},
  {from: '/products/Telstar-CT', to: '/produkte/Telstar-CT'},
  {from: '/rma-application-form', to: '/rma-antragsformulare'},
  {from: '/third-party-products', to: '/drittprodukte'},
  {from: '/third-party-products/current-transformers', to: '/drittprodukte/Stromwandler'},
  {from: '/third-party-products/meter-plug-in-terminals', to: '/drittprodukte/zaehlersteckklemmen-nimbus-100A'},
  {from: '/third-party-products/stand-foundation', to: '/drittprodukte/standfuss-fundamente'},
  {from: '/third-party-systems', to: '/drittsysteme'},
  {from: '/third-party-systems/askoma', to: '/drittsysteme/askoma'},
  {from: '/third-party-systems/bexio', to: '/drittsysteme/bexio'},
  {from: '/third-party-systems/clever-pv', to: '/drittsysteme/clever-pv'},
  {from: '/third-party-systems/digital-republic', to: '/drittsysteme/digital-republic'},
  {from: '/third-party-systems/egonline', to: '/drittsysteme/egonline'},
  {from: '/third-party-systems/fairwalter', to: '/drittsysteme/fairwalter'},
  {from: '/third-party-systems/greenpocket', to: '/drittsysteme/greenpocket'},
  {from: '/third-party-systems/ibm-node-red', to: '/drittsysteme/ibm-node-red'},
  {from: '/third-party-systems/imovatec', to: '/drittsysteme/imovatec'},
  {from: '/third-party-systems/limmobi', to: '/drittsysteme/limmobi'},
  {from: '/third-party-systems/loxone', to: '/drittsysteme/loxone'},
  {from: '/third-party-systems/microsoft-excel', to: '/drittsysteme/microsoft-excel'},
  {from: '/third-party-systems/piskelapp', to: '/drittsysteme/piskelapp'},
  {from: '/third-party-systems/smartfox', to: '/drittsysteme/smartfox'},
  {from: '/third-party-systems/smartred', to: '/drittsysteme/smartred'},
  {from: '/third-party-systems/solarmanager', to: '/drittsysteme/solarmanager'},
  {from: '/third-party-systems/soleco', to: '/drittsysteme/soleco'},
  {from: '/third-party-systems/switzercloud-colibird', to: '/drittsysteme/switzercloud-colibird'},
  {from: '/third-party-systems/symcon', to: '/drittsysteme/symcon'},
  {from: '/third-party-systems/trueenergy', to: '/drittsysteme/trueenergy-as'},
  {from: '/third-party-systems/whatwatt', to: '/drittsysteme/whatwatt'},
  {from: '/third-party-systems/zaehlerfreunde', to: '/drittsysteme/zaehlerfreunde'},
  {from: '/third-party-systems/zerofy', to: '/drittsysteme/zerofy'},
  {from: '/third-party-systems/zevvy', to: '/drittsysteme/zevvy'},
  {from: '/troubleshooting/billing-error-messages', to: '/stoerungsbehebung/billing-fehlermeldungen'},
  {from: '/troubleshooting/differences-with-the-eletricity-supplier', to: '/stoerungsbehebung/differenzen-mit-dem-ew'},
  {from: '/troubleshooting/m-bus-gateway-failures', to: '/stoerungsbehebung/mbus-gateway-stoerungen'},
  {from: '/troubleshooting/meter-offline', to: '/stoerungsbehebung/zaehler-offline'},
  {from: '/troubleshooting/pico-errors', to: '/stoerungsbehebung/pico-fehler'},
  {from: '/troubleshooting/telstar-ct-setup-issues', to: '/stoerungsbehebung/telstar-ct-inbetriebnahmefehler'},
  {from: '/troubleshooting/visualization-error', to: '/stoerungsbehebung/visualisierungsfehler'},
];
