import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Die Sidebar bildet die Struktur des bisherigen Google-Sites-Wikis ab.
 * Wird beim Ausbau der Inhalte (Phase 2) erweitert.
 */
const sidebars: SidebarsConfig = {
  wikiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
